// 1. Алгоритмическая задача
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 3 and 4, the first 10 terms of the Fibonacci-like sequence will be: 3, 4, 7, 11, 18, 29, 47, 76, 123, 199, ... . By considering the terms in this sequence whose values do not exceed seven million, find the sum of the even-valued terms.

function fibonacci() {
  let prev = 3;
  let curr = 4;
  let sum = 0;
  while (curr <= 7000000) {
    if (curr % 2 === 0) {
      sum += curr;
    }
    let nextCurr = curr + prev;
    prev = curr;
    curr = nextCurr;
  }
  return sum;
}

console.log(fibonacci());